// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AddAutoToActorCommand","status":true,"description":"Add 'Auto' command on the top or bottom of Actor Command","parameters":{"commandName":"Auto Select","autoCommandPos":"0"}},
{"name":"EventEffects","status":true,"description":"[Ver 1.1.3] set various effects to events and player","parameters":{}},
{"name":"wasdKeyMZ","status":true,"description":"It is a plugin that corresponds to the wasd move.","parameters":{}}
];
